uploads = []
generated = []

[[outputs]]
id = "Gt-nzuSLmdKZkc_hnFrTi"
uri = "file://client/src/assets/cinematic-bg.jpg"
type = "image"
title = "dark moody abstract cinematic lighting subtle film grain background premium"

[[outputs]]
id = "3cyDoxYzf5F7417BGhqp4"
uri = "file://client/src/assets/project-1.jpg"
type = "image"
title = "cinematic moody dark film set dramatic lighting"

[[outputs]]
id = "0JHhtiFK3S1dOi41NCSuR"
uri = "file://client/src/assets/project-2.jpg"
type = "image"
title = "cinematic moody dark studio camera lens close up"

[[outputs]]
id = "YD7qIBoozYHd4YxSi8Hff"
uri = "file://client/src/assets/project-3.jpg"
type = "image"
title = "cinematic moody dark script writing desk vintage"

[[outputs]]
id = "luJ3kA5oCuJcavnh-fVVo"
uri = "file://client/src/assets/project-4.jpg"
type = "image"
title = "cinematic moody dark clapperboard production scene"

[[outputs]]
id = "7kaEZbNNzu8rVZmJljdM3"
uri = "file://client/src/assets/project-1-new.jpg"
type = "image"
title = "cinematic thriller drama old house looking scary"

[[outputs]]
id = "pNwgotqOf4ayOBuSv4TPU"
uri = "file://client/src/assets/project-2-new.jpg"
type = "image"
title = "sci-fi horror conceptual abstract therapy brain"

[[outputs]]
id = "0lD_vBMCgP_Jhuz6_E56f"
uri = "file://client/src/assets/project-3-new.jpg"
type = "image"
title = "music drama singer fado lisbon club stage"

[[outputs]]
id = "1IJvqzP62uMsyxFR1ZiWx"
uri = "file://client/src/assets/project-4-new.jpg"
type = "image"
title = "action sci-fi agent cyber futuristic"
