import { randomBytes } from "node:crypto";
import type { Readable } from "node:stream";

/**
 * The only thing the application knows about where bytes live. Keys are
 * generated by the Files domain (never by users), objects are written once
 * and never rewritten, and nothing here produces a URL.
 *
 * Implementations: `local-file-storage.ts` (a directory; development, tests,
 * or a persistent volume). Production object storage implements the same
 * four methods behind `storage-factory.ts`; the domain layer cannot tell the
 * difference.
 */
export interface FileStorage {
  /** Writes a new object. Rejects with ObjectAlreadyExistsError if `key` exists. */
  put(key: string, source: Readable): Promise<void>;
  /** Opens an existing object for reading. Rejects with ObjectNotFoundError. */
  open(key: string): Promise<Readable>;
  /** Removes an object. Idempotent: a missing object is not an error. */
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export class StorageError extends Error {}
export class ObjectNotFoundError extends StorageError {
  constructor(readonly key: string) {
    super(`Object not found: ${key}`);
  }
}
export class ObjectAlreadyExistsError extends StorageError {
  constructor(readonly key: string) {
    super(`Object already exists: ${key}`);
  }
}
export class InvalidStorageKeyError extends StorageError {
  constructor(readonly key: string) {
    super("Invalid storage key.");
  }
}

/**
 * Keys are 32 random bytes as hex, fanned out two levels (`ab/cd/abcd…`).
 * They carry no filename, id, project or user information, so knowing one
 * reveals nothing and guessing one is infeasible.
 */
export const STORAGE_KEY_PATTERN = /^[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9]{64}$/;

export function generateStorageKey(): string {
  const hex = randomBytes(32).toString("hex");
  return `${hex.slice(0, 2)}/${hex.slice(2, 4)}/${hex}`;
}

/** Every adapter validates keys before touching its backend. */
export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key)) throw new InvalidStorageKeyError(key);
}
