import { randomBytes } from "node:crypto";
import type { Readable } from "node:stream";

/**
 * The only thing the application knows about where bytes live. Keys are
 * generated by the Files domain (never by users), objects are written once
 * and never rewritten, and nothing here produces a URL.
 *
 * Implementations: `local-file-storage.ts` (a directory; development, tests,
 * or a persistent volume). Production object storage implements the same
 * four methods behind `storage-factory.ts`; the domain layer cannot tell the
 * difference.
 */
export interface FileStorage {
  /** Writes a new object. Rejects with ObjectAlreadyExistsError if `key` exists. */
  put(key: string, source: Readable): Promise<void>;
  /** Opens an existing object for reading. Rejects with ObjectNotFoundError. */
  open(key: string): Promise<Readable>;
  /** Removes an object. Idempotent: a missing object is not an error. */
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export class StorageError extends Error {}
export class ObjectNotFoundError extends StorageError {
  constructor(readonly key: string) {
    super(`Object not found: ${key}`);
  }
}
export class ObjectAlreadyExistsError extends StorageError {
  constructor(readonly key: string) {
    super(`Object already exists: ${key}`);
  }
}
export class InvalidStorageKeyError extends StorageError {
  constructor(readonly key: string) {
    super("Invalid storage key.");
  }
}
export class InvalidStoragePrefixError extends StorageError {
  constructor(readonly prefix: string) {
    super(
      "Invalid storage prefix: use slash-separated segments of letters, digits, dot, underscore or hyphen, each starting with a letter or digit.",
    );
  }
}

/**
 * Keys are 32 random bytes as hex, fanned out two levels (`ab/cd/abcd…`).
 * They carry no filename, id, project or user information, so knowing one
 * reveals nothing and guessing one is infeasible.
 */
export const STORAGE_KEY_PATTERN = /^[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9]{64}$/;

export function generateStorageKey(): string {
  const hex = randomBytes(32).toString("hex");
  return `${hex.slice(0, 2)}/${hex.slice(2, 4)}/${hex}`;
}

/** Every adapter validates keys before touching its backend. */
export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key)) throw new InvalidStorageKeyError(key);
}

/**
 * A key prefix an object-storage adapter may prepend, so one bucket can hold
 * more than one environment's objects when the platform offers no stronger
 * separation. Slash-separated segments of `[A-Za-z0-9._-]`, each beginning
 * with a letter or digit: that admits `dev/` and `vault/production/` and
 * refuses a leading slash, an empty segment, `..`, a backslash or whitespace.
 */
export const STORAGE_PREFIX_PATTERN =
  /^[A-Za-z0-9][A-Za-z0-9._-]*(\/[A-Za-z0-9][A-Za-z0-9._-]*)*\/?$/;

/**
 * Normalises a configured prefix to either `""` or a value ending in exactly
 * one `/`, so an adapter can concatenate it with a storage key unconditionally.
 */
export function normaliseStoragePrefix(prefix: string | undefined): string {
  const trimmed = (prefix ?? "").trim();
  if (trimmed === "") return "";
  if (!STORAGE_PREFIX_PATTERN.test(trimmed))
    throw new InvalidStoragePrefixError(trimmed);
  return trimmed.endsWith("/") ? trimmed : `${trimmed}/`;
}
